/**
 * Multi-Agent Runtime Core Types for Sentinel Nova (Day 5A)
 *
 * Defines the foundational types for agent identity, execution lifecycle,
 * contexts, action proposals, results, and observability traces.
 */

import { UserPlanningProfile } from '../profileStore';
import {
  Task,
  Goal,
  Project,
  CalendarStatusResponse,
  CalendarEvent,
  AvailabilityResult,
} from '../../src/types';

export type AgentId = string;

export type AgentCapability =
  | 'planning'
  | 'prioritization'
  | 'memory'
  | 'scheduling'
  | 'analysis'
  | 'review'
  | 'recovery'
  | 'inspection'
  | 'testing'
  | 'task_decomposition'
  | 'sequencing'
  | 'goal_alignment'
  | 'schedule_awareness'
  | 'urgency_analysis'
  | 'impact_analysis'
  | 'task_ranking'
  | 'decision_support'
  | 'memory_retrieval'
  | 'memory_update'
  | 'memory_creation'
  | 'memory_deduplication'
  | 'memory_lifecycle'
  | 'context_recall'
  | 'preference_detection'
  | 'availability_analysis'
  | 'calendar_awareness'
  | 'workload_balancing'
  | 'deadline_management'
  | 'focus_window_matching'
  | 'schedule_optimization'
  | 'conflict_detection'
  | 'failure_analysis'
  | 'failure_classification'
  | 'recovery_planning'
  | 'retry_analysis'
  | 'alternative_action'
  | 'execution_recovery'
  | 'self_correction'
  | 'recovery_decision_support';

export type AgentStatus = 'idle' | 'running' | 'completed' | 'failed' | 'timeout';

export type ExecutionLifecycleStatus =
  | 'REQUESTED'
  | 'CONTEXT_BUILDING'
  | 'AGENT_SELECTED'
  | 'RUNNING'
  | 'RESULT_RECEIVED'
  | 'COMPLETED'
  | 'FAILED';

export type AgentActionType =
  | 'CREATE_TASK'
  | 'UPDATE_TASK'
  | 'SCHEDULE_TASK'
  | 'UPDATE_GOAL'
  | 'CREATE_PROJECT'
  | 'SEND_NOTIFICATION'
  | 'INSPECT_CONTEXT'
  | 'COMPLETE_TASK'
  | 'REOPEN_TASK'
  | 'MEMORY_CREATE'
  | 'MEMORY_UPDATE'
  | 'MEMORY_ARCHIVE'
  | 'MEMORY_DELETE'
  | 'MEMORY_RETRIEVE'
  | 'MEMORY_IGNORE'
  | 'MEMORY_REVIEW_REQUIRED'
  | 'RECOVERY_RETRY'
  | 'RECOVERY_ADJUST'
  | 'RECOVERY_REPLAN'
  | 'RECOVERY_ALTERNATIVE'
  | 'RECOVERY_ASK_USER'
  | 'RECOVERY_ABORT';

export type RiskLevel = 'low' | 'medium' | 'high';

/**
 * Action Proposal generated by an agent.
 * Day 5A Safety Mandate: Actions are PROPOSALS ONLY.
 * Agents NEVER execute mutations autonomously.
 */
export interface AgentAction {
  actionId: string;
  type: AgentActionType;
  description: string;
  target: string;
  parameters: Record<string, unknown>;
  riskLevel: RiskLevel;
  requiresConfirmation: boolean;
  sourceAgentId: string;
}

export interface AgentError {
  code: string;
  message: string;
  details?: unknown;
}

export interface AgentMetadata {
  id: AgentId;
  name: string;
  description: string;
  version: string;
  capabilities: AgentCapability[];
  timeoutMs?: number;
}

export interface AgentTrace {
  agentId: string;
  executionId: string;
  startTime: number;
  endTime: number;
  durationMs: number;
  status: AgentStatus;
  success: boolean;
  confidence?: number;
  warnings?: string[];
  error?: AgentError;
}

export interface AgentResult<T = unknown> {
  success: boolean;
  agentId: string;
  executionId: string;
  output: T;
  confidence?: number; // Normalized 0.0 to 1.0
  actions: AgentAction[];
  warnings: string[];
  errors: AgentError[];
  metadata: Record<string, unknown>;
  durationMs: number;
}

export interface AgentContext {
  userId: string;
  requestId: string;
  executionId: string;
  userRequest: string;
  timestamp: string; // ISO 8601
  timezone: string;
  profile?: UserPlanningProfile | null;
  goals?: Goal[];
  projects?: Project[];
  tasks?: Task[];
  calendarStatus?: CalendarStatusResponse | null;
  calendarEvents?: CalendarEvent[];
  availability?: AvailabilityResult | null;
  memoryContext?: {
    relevantMemories: import('./agents/memoryTypes').SanitizedMemory[];
    retrievalQuery?: string;
  };
  priorResults?: AgentResult[];
  allowedCapabilities?: AgentCapability[];
  parameters?: Record<string, unknown>;
}

export interface ContextScopeOptions {
  includeProfile?: boolean;
  includeTasks?: boolean;
  activeTasksOnly?: boolean;
  includeGoals?: boolean;
  includeProjects?: boolean;
  includeCalendar?: boolean;
  includeAvailability?: boolean;
  includeMemory?: boolean;
  memoryQuery?: string;
  dateStr?: string;
}

export interface AgentRequest {
  requestId: string;
  userRequest: string;
  preferredAgentId?: string;
  requiredCapabilities?: AgentCapability[];
  scope?: ContextScopeOptions;
  parameters?: Record<string, unknown>;
}

export interface OrchestrationResult {
  success: boolean;
  requestId: string;
  executionId: string;
  lifecycleStatus: ExecutionLifecycleStatus;
  agentResults: AgentResult[];
  proposedActions: AgentAction[];
  traces: AgentTrace[];
  summary: string;
  durationMs: number;
  error?: AgentError;
}
