/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: string;
  agentSteps?: { agentId: string; name: string; durationMs: number }[];
  decisionTree?: {
    options: { name: string; chosen: boolean; confidence: number; pros: string[]; cons: string[] }[];
  };
  confidenceScore?: {
    overall: number;
    reasoningQuality: number;
    dataQuality: number;
    riskLevel: 'low' | 'medium' | 'high' | 'critical';
  };
  explainability?: {
    why: string;
    benefits: string[];
    risks: string[];
    nextSteps: string[];
  };
  insightsGenerated?: { id: string; text: string; type: 'info' | 'warning' | 'success' }[];
  observability?: {
    tokenUsage?: { total: number };
    executionTimeMs?: number;
    reasoningDepth?: number;
  };
}

export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: string;
}

export interface Task {
  id: string;
  title: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'todo' | 'in_progress' | 'done';
  estimatedHours: number;
  pastCompletionRate?: number; // percentage
  daysRemaining: number;
  difficulty: 'easy' | 'medium' | 'hard';
  dependencies: string[]; // List of task IDs or titles
  
  // Predictive metrics
  completionProbability: number; // calculated %
  predictedCompletionDate: string;
  delayRisk: 'low' | 'medium' | 'high' | 'critical';
  suggestedReorderIdx?: number;
  timeAllocationHours?: number;
}

export interface Goal {
  id: string;
  title: string;
  targetDate: string;
  category: 'career' | 'technical' | 'project' | 'education';
  progress: number; // 0-100
  
  // Predictive metrics
  successProbability: number; // calculated %
  failureProbability: number; // calculated %
  predictedMilestoneDelay: boolean;
  aiRecoveryPlan: string[];
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  reasoning: string;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'active' | 'completed' | 'on_hold';
  completionRate: number;
  expectedEndDate: string;
  
  // Predictive metrics
  estimatedLaunchProbability: number; // %
  bottlenecks: string[];
  skillGrowthFactor: number; // expected scale contribution
}

export interface Opportunity {
  id: string;
  title: string;
  company: string;
  type: 'Internship' | 'Full-Time' | 'Hackathon' | 'Scholarship' | 'Course';
  deadline: string;
  url?: string;
  
  // Predictive matching metrics
  fitScore: number; // fit score generated by matching
  expectedSuccess: number; // chance of securing %
  applicationConfidence: number; // %
  careerImpactScore: number; // 1-100 impact on goals
  deadlineUrgency: 'low' | 'medium' | 'high' | 'critical';
}

export interface CareerMetrics {
  currentReadiness: number; // 1-100
  forecast30Days: number;
  forecast90Days: number;
  interviewProbability: number; // %
  futureSalaryProjection: { year: number; salary: number }[];
  skillGrowth: { name: string; currentScore: number; targetScore: number; predicted90Days: number }[];
}

export interface ResumeMetrics {
  atsScore: number;
  atsForecast30Days: number;
  missingSkills: string[];
  hiringProbability: number;
  improvementTrend: { date: string; score: number }[];
}

export interface BurnoutMetrics {
  burnoutRisk: 'low' | 'medium' | 'high' | 'critical';
  burnoutScore: number; // 0-100
  recoverySuggestions: string[];
  productivityTrend: { date: string; value: number; predictedValue: number }[];
}

export interface PredictionEngineMetrics {
  historicalAccuracy: number; // percentage
  precision: number;
  recall: number;
  f1Score: number;
  predictionDrift: number; // indicator of shifts
}
