/**
 * Specialized Memory Agent Types for Sentinel Nova (Day 5B.3)
 *
 * Defines strongly typed contracts for persistent, user-isolated memory:
 * memory categories, authority levels, sensitivity classification,
 * lifecycle states, retrieval scoring, duplicate detection, and action proposals.
 */

export type MemoryType =
  | 'preference'
  | 'goal_context'
  | 'project_context'
  | 'task_pattern'
  | 'working_style'
  | 'scheduling_preference'
  | 'constraint'
  | 'decision'
  | 'instruction'
  | 'fact'
  | 'temporary_context'
  | 'execution_context'
  | 'learned_pattern';

export type MemoryImportance = 'low' | 'medium' | 'high' | 'critical';

export type MemoryStatus = 'active' | 'archived' | 'superseded' | 'deleted';

export type MemorySource =
  | 'user_confirmed'
  | 'user_explicit'
  | 'system_derived'
  | 'agent_proposed'
  | 'agent_inferred';

export type MemorySensitivity = 'normal' | 'sensitive' | 'restricted';

export type MemoryOperation =
  | 'retrieve'
  | 'create'
  | 'update'
  | 'archive'
  | 'delete'
  | 'ignore'
  | 'review_required';

/**
 * Persisted server-side Memory entity (MemoryRecord).
 * Backed by data/memories.json.
 */
export interface ServerMemory {
  id: string; // Server-generated 'mem_...'
  userId: string; // Authenticated user ID (strictly isolated)
  type: MemoryType;
  content: string; // Max 1000 characters, normalized
  importance: MemoryImportance;
  confidence: number; // 0.0 - 1.0 (clamped)
  status: MemoryStatus;
  source: MemorySource;
  sourceReference: string; // Safe provenance (e.g., 'planning_profile', 'user_chat') - max 200 chars
  sensitivity: MemorySensitivity;
  tags: string[]; // Bounded array of keyword tags
  explicit: boolean; // Mandatory: true for user stated/saved, false for inferred/derived
  createdAt: string; // ISO 8601
  updatedAt: string; // ISO 8601
  lastAccessedAt: string; // ISO 8601
  expiresAt?: string | null; // ISO 8601 (optional, for temporary_context)
  accessCount: number;
  metadata?: Record<string, unknown>;
}

export type MemoryRecord = ServerMemory;

/**
 * Input payload for creating or updating memories.
 */
export interface MemoryInput {
  userId?: string; // Trust boundary check: rejected if does not match authenticated user
  type?: MemoryType;
  content?: string;
  importance?: MemoryImportance;
  confidence?: number;
  status?: MemoryStatus;
  source?: MemorySource;
  sourceReference?: string;
  sensitivity?: MemorySensitivity;
  tags?: string[];
  explicit?: boolean;
  expiresAt?: string | null;
  metadata?: Record<string, unknown>;
}

/**
 * Retrieval options for deterministic memory recall.
 */
export interface MemoryRetrieveOptions {
  query?: string;
  types?: MemoryType[];
  tags?: string[];
  limit?: number; // Default 5, max 10
  minConfidence?: number;
  includeArchived?: boolean;
  includeDeleted?: boolean;
  includeSuperseded?: boolean;
  referenceTime?: string; // ISO string for freshness calculation (defaults to now)
}

/**
 * Scored Memory Item enriched with deterministic relevance factors.
 */
export interface ScoredMemoryItem extends ServerMemory {
  relevanceScore: number; // 0.0 - 1.0
  queryMatchScore: number; // 0.0 - 1.0
  lexicalScore?: number; // 0.0 - 1.0
  freshnessScore: number; // 0.0 - 1.0
  contextualBoost?: number; // 0.0 - 1.0
  matchReason?: string;
}

/**
 * Sanitized memory item exposed to other agents and external APIs.
 * Guarantees zero sensitive secrets, cookies, or auth tokens.
 */
export interface ScoredMemoryItemSafe {
  memoryId: string;
  type: MemoryType;
  content: string;
  relevanceScore: number;
  confidence: number;
  explicit: boolean;
  source: MemorySource;
  importance?: MemoryImportance | number;
  tags?: string[];
}

/**
 * Detailed memory conflict detected between two memory records.
 */
export interface MemoryConflict {
  memoryA: ServerMemory;
  memoryB: ServerMemory;
  conflictReason: string;
  authoritativeMemoryId: string;
  authoritativeReason: string;
}

/**
 * Safe report of a memory conflict for agent output.
 */
export interface MemoryConflictReport {
  memoryIdA: string;
  memoryIdB: string;
  reason: string;
  authoritativeMemoryId: string;
  rationale: string;
}

/**
 * Memory Proposal generated by the Memory Agent.
 * Day 5B.3 Safety Mandate: PROPOSALS ONLY.
 * The Memory Agent NEVER executes persistent store mutations autonomously.
 */
export interface MemoryProposal {
  operation: MemoryOperation;
  targetMemoryId?: string;
  type: MemoryType;
  content: string;
  importance: MemoryImportance;
  confidence: number;
  source: MemorySource;
  sourceReference: string;
  sensitivity: MemorySensitivity;
  requiresConfirmation: boolean;
  rationale: string;
  conflictWithMemoryId?: string;
  tags?: string[];
  explicit?: boolean;
}

/**
 * Structured output produced by MemoryAgent.execute().
 */
export interface MemoryAgentOutput {
  primaryIntent: 'retrieve' | 'remember' | 'forget' | 'update' | 'ignore' | 'inspect';
  retrievedMemories: ScoredMemoryItem[];
  relevantMemories: ScoredMemoryItemSafe[];
  rankedMemories: ScoredMemoryItemSafe[];
  conflicts: MemoryConflictReport[];
  memorySummary: string;
  proposedMemories: MemoryProposal[];
  proposals: MemoryProposal[]; // Alias for backward compatibility
  summary: string;
  decisionExplanation: string;
  confidence: number; // 0.0 - 1.0
  warnings: string[];
  reasoningSource: 'deterministic' | 'gemini_enhanced' | 'deterministic_fallback';
  metadata?: Record<string, unknown>;
}

/**
 * Sanitized memory representation safe to share across agent contexts
 * and external reasoning boundaries without exposing raw database IDs or secrets.
 */
export interface SanitizedMemory {
  id?: string;
  type: MemoryType;
  content: string;
  importance: MemoryImportance;
  confidence: number;
  source: MemorySource;
  freshnessScore?: number;
  relevanceScore?: number;
}
